/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Font;

/**
 *
 * @author Matheus
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_fundo = new javax.swing.JPanel();
        text_title = new javax.swing.JLabel();
        main_panel = new javax.swing.JTabbedPane();
        panel_texto = new javax.swing.JDesktopPane();
        p_panel_texto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_texto = new javax.swing.JTextArea();
        label_nome_arquivo = new javax.swing.JLabel();
        input_nome_arquivo = new javax.swing.JTextField();
        label_caminho_arquivo = new javax.swing.JLabel();
        input_caminho_arquivo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panel_arquivo = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FGM Compacter");
        setBackground(new java.awt.Color(32, 32, 36));
        setForeground(new java.awt.Color(32, 32, 36));
        setResizable(false);

        main_fundo.setBackground(new java.awt.Color(18, 18, 20));

        text_title.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        text_title.setForeground(new java.awt.Color(255, 255, 255));
        text_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_title.setText("FGM Compacter");
        text_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel_texto.setBackground(new java.awt.Color(137, 108, 235));

        p_panel_texto.setBackground(new java.awt.Color(32, 32, 36));

        area_texto.setColumns(20);
        area_texto.setRows(5);
        area_texto.setToolTipText("Digite aqui um texto para compactar");
        area_texto.setName(""); // NOI18N
        jScrollPane1.setViewportView(area_texto);

        label_nome_arquivo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        label_nome_arquivo.setForeground(new java.awt.Color(255, 255, 255));
        label_nome_arquivo.setText("Nome do Arquivo :");
        label_nome_arquivo.setPreferredSize(new java.awt.Dimension(150, 20));

        input_nome_arquivo.setToolTipText("Informe o nome do arquivo de saida");

        label_caminho_arquivo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        label_caminho_arquivo.setForeground(new java.awt.Color(255, 255, 255));
        label_caminho_arquivo.setText("Caminho do Arquivo");
        label_caminho_arquivo.setPreferredSize(new java.awt.Dimension(150, 20));

        input_caminho_arquivo.setEditable(false);

        jButton1.setText("Chose");

        javax.swing.GroupLayout p_panel_textoLayout = new javax.swing.GroupLayout(p_panel_texto);
        p_panel_texto.setLayout(p_panel_textoLayout);
        p_panel_textoLayout.setHorizontalGroup(
            p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_panel_textoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(p_panel_textoLayout.createSequentialGroup()
                        .addGroup(p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_panel_textoLayout.createSequentialGroup()
                                .addComponent(label_nome_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(input_nome_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_panel_textoLayout.createSequentialGroup()
                                .addComponent(label_caminho_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(input_caminho_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 468, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p_panel_textoLayout.setVerticalGroup(
            p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_panel_textoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_nome_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nome_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_caminho_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_caminho_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        panel_texto.setLayer(p_panel_texto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel_textoLayout = new javax.swing.GroupLayout(panel_texto);
        panel_texto.setLayout(panel_textoLayout);
        panel_textoLayout.setHorizontalGroup(
            panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_panel_texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_textoLayout.setVerticalGroup(
            panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_panel_texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_panel.addTab("Texto", panel_texto);

        jPanel1.setBackground(new java.awt.Color(32, 32, 36));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        panel_arquivo.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel_arquivoLayout = new javax.swing.GroupLayout(panel_arquivo);
        panel_arquivo.setLayout(panel_arquivoLayout);
        panel_arquivoLayout.setHorizontalGroup(
            panel_arquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_arquivoLayout.setVerticalGroup(
            panel_arquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_panel.addTab("Arquivo", panel_arquivo);

        javax.swing.GroupLayout main_fundoLayout = new javax.swing.GroupLayout(main_fundo);
        main_fundo.setLayout(main_fundoLayout);
        main_fundoLayout.setHorizontalGroup(
            main_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_fundoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(main_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(main_fundoLayout.createSequentialGroup()
                        .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        main_fundoLayout.setVerticalGroup(
            main_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_fundoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(text_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_texto;
    private javax.swing.JTextField input_caminho_arquivo;
    private javax.swing.JTextField input_nome_arquivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_caminho_arquivo;
    private javax.swing.JLabel label_nome_arquivo;
    private javax.swing.JPanel main_fundo;
    private javax.swing.JTabbedPane main_panel;
    private javax.swing.JPanel p_panel_texto;
    private javax.swing.JDesktopPane panel_arquivo;
    private javax.swing.JDesktopPane panel_texto;
    private javax.swing.JLabel text_title;
    // End of variables declaration//GEN-END:variables
}
