/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Container;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import models.FGM_Compacter;
import models.Save;

/**
 *
 * @author Matheus
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setViewCompactar();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_open_path = new javax.swing.JDialog();
        main_fundo = new javax.swing.JPanel();
        text_title = new javax.swing.JLabel();
        main_panel = new javax.swing.JTabbedPane();
        panel_texto = new javax.swing.JDesktopPane();
        p_panel_texto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_texto_mensagem = new javax.swing.JTextArea();
        label_nome_arquivo = new javax.swing.JLabel();
        input_texto_nome_arquivo = new javax.swing.JTextField();
        label_caminho_arquivo = new javax.swing.JLabel();
        input_texto_caminho_arquivo = new javax.swing.JTextField();
        btn_choose_path = new javax.swing.JButton();
        btn_texto_CD = new javax.swing.JButton();
        panel_arquivo = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        label_arquivo_nome_C = new javax.swing.JLabel();
        input_arquivo_nome_arquivo = new javax.swing.JTextField();
        label_arquivo_path_arquivo = new javax.swing.JLabel();
        input_arquivo_caminho_arquivo = new javax.swing.JTextField();
        btn_choose_path1 = new javax.swing.JButton();
        btn_arquivo_CD = new javax.swing.JButton();
        label_arquivo_caminho_CD = new javax.swing.JLabel();
        input_arquivo_a_compactar = new javax.swing.JTextField();
        btn_choose_path2 = new javax.swing.JButton();
        fundo_area = new javax.swing.JScrollPane();
        area_arquivo_texto_D = new javax.swing.JTextArea();
        label_select_op = new javax.swing.JLabel();
        select_op = new javax.swing.JComboBox<>();
        icon = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout dialog_open_pathLayout = new javax.swing.GroupLayout(dialog_open_path.getContentPane());
        dialog_open_path.getContentPane().setLayout(dialog_open_pathLayout);
        dialog_open_pathLayout.setHorizontalGroup(
            dialog_open_pathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialog_open_pathLayout.setVerticalGroup(
            dialog_open_pathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FGM Compacter");
        setBackground(new java.awt.Color(32, 32, 36));
        setForeground(new java.awt.Color(32, 32, 36));
        setResizable(false);

        main_fundo.setBackground(new java.awt.Color(18, 18, 20));

        text_title.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        text_title.setForeground(new java.awt.Color(255, 255, 255));
        text_title.setText("FGM Compacter");
        text_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        main_panel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        panel_texto.setBackground(new java.awt.Color(137, 108, 235));

        p_panel_texto.setBackground(new java.awt.Color(32, 32, 36));

        area_texto_mensagem.setColumns(20);
        area_texto_mensagem.setRows(5);
        area_texto_mensagem.setToolTipText("Digite aqui um texto para compactar");
        area_texto_mensagem.setName(""); // NOI18N
        jScrollPane1.setViewportView(area_texto_mensagem);

        label_nome_arquivo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        label_nome_arquivo.setForeground(new java.awt.Color(255, 255, 255));
        label_nome_arquivo.setText("Nome do Arquivo :");
        label_nome_arquivo.setPreferredSize(new java.awt.Dimension(150, 20));

        input_texto_nome_arquivo.setToolTipText("Informe o nome do arquivo de saida");

        label_caminho_arquivo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        label_caminho_arquivo.setForeground(new java.awt.Color(255, 255, 255));
        label_caminho_arquivo.setText("Caminho do Arquivo");
        label_caminho_arquivo.setPreferredSize(new java.awt.Dimension(150, 20));

        input_texto_caminho_arquivo.setEditable(false);

        btn_choose_path.setBackground(new java.awt.Color(137, 108, 235));
        btn_choose_path.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.png"))); // NOI18N
        btn_choose_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choose_pathActionPerformed(evt);
            }
        });

        btn_texto_CD.setBackground(new java.awt.Color(137, 108, 235));
        btn_texto_CD.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        btn_texto_CD.setForeground(new java.awt.Color(255, 255, 255));
        btn_texto_CD.setText("Compactar");
        btn_texto_CD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_texto_CDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_panel_textoLayout = new javax.swing.GroupLayout(p_panel_texto);
        p_panel_texto.setLayout(p_panel_textoLayout);
        p_panel_textoLayout.setHorizontalGroup(
            p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_panel_textoLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(p_panel_textoLayout.createSequentialGroup()
                            .addComponent(label_nome_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(input_texto_nome_arquivo))
                        .addGroup(p_panel_textoLayout.createSequentialGroup()
                            .addComponent(label_caminho_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(input_texto_caminho_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_choose_path, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_texto_CD, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        p_panel_textoLayout.setVerticalGroup(
            p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_panel_textoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_texto_nome_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nome_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_choose_path, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_caminho_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(input_texto_caminho_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_texto_CD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_texto.setLayer(p_panel_texto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel_textoLayout = new javax.swing.GroupLayout(panel_texto);
        panel_texto.setLayout(panel_textoLayout);
        panel_textoLayout.setHorizontalGroup(
            panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_panel_texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_textoLayout.setVerticalGroup(
            panel_textoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_panel_texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_panel.addTab("Texto", panel_texto);

        jPanel1.setBackground(new java.awt.Color(32, 32, 36));

        label_arquivo_nome_C.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        label_arquivo_nome_C.setForeground(new java.awt.Color(255, 255, 255));
        label_arquivo_nome_C.setText("Nome do Arquivo Compactado:");
        label_arquivo_nome_C.setPreferredSize(new java.awt.Dimension(190, 20));

        input_arquivo_nome_arquivo.setToolTipText("Informe o nome do arquivo de saida");
        input_arquivo_nome_arquivo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                input_arquivo_nome_arquivoPropertyChange(evt);
            }
        });
        input_arquivo_nome_arquivo.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                input_arquivo_nome_arquivoVetoableChange(evt);
            }
        });

        label_arquivo_path_arquivo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        label_arquivo_path_arquivo.setForeground(new java.awt.Color(255, 255, 255));
        label_arquivo_path_arquivo.setText("Caminho do Arquivo");
        label_arquivo_path_arquivo.setPreferredSize(new java.awt.Dimension(190, 20));

        input_arquivo_caminho_arquivo.setEditable(false);

        btn_choose_path1.setBackground(new java.awt.Color(137, 108, 235));
        btn_choose_path1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.png"))); // NOI18N
        btn_choose_path1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choose_path1ActionPerformed(evt);
            }
        });

        btn_arquivo_CD.setBackground(new java.awt.Color(137, 108, 235));
        btn_arquivo_CD.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        btn_arquivo_CD.setForeground(new java.awt.Color(255, 255, 255));
        btn_arquivo_CD.setText("Compactar");
        btn_arquivo_CD.setDoubleBuffered(true);
        btn_arquivo_CD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_arquivo_CDActionPerformed(evt);
            }
        });

        label_arquivo_caminho_CD.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        label_arquivo_caminho_CD.setForeground(new java.awt.Color(255, 255, 255));
        label_arquivo_caminho_CD.setText("Selecione o arquivo p/ compactar");
        label_arquivo_caminho_CD.setPreferredSize(new java.awt.Dimension(190, 20));

        input_arquivo_a_compactar.setEditable(false);
        input_arquivo_a_compactar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                input_arquivo_a_compactarPropertyChange(evt);
            }
        });

        btn_choose_path2.setBackground(new java.awt.Color(137, 108, 235));
        btn_choose_path2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.png"))); // NOI18N
        btn_choose_path2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choose_path2ActionPerformed(evt);
            }
        });

        fundo_area.setBackground(new java.awt.Color(32, 32, 36));

        area_arquivo_texto_D.setColumns(20);
        area_arquivo_texto_D.setRows(5);
        fundo_area.setViewportView(area_arquivo_texto_D);

        label_select_op.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label_select_op.setForeground(new java.awt.Color(255, 255, 255));
        label_select_op.setText("Selecione a Operação:");

        select_op.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        select_op.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compactar", "Descompactar" }));
        select_op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_opActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fundo_area)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(label_arquivo_path_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(input_arquivo_caminho_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_choose_path1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_arquivo_nome_C, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_arquivo_caminho_CD, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(input_arquivo_nome_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(input_arquivo_a_compactar, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_choose_path2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(select_op, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_select_op, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_arquivo_CD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_choose_path2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label_arquivo_caminho_CD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(input_arquivo_a_compactar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_arquivo_nome_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_arquivo_nome_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_select_op)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_choose_path1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_arquivo_path_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(input_arquivo_caminho_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_arquivo_CD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fundo_area, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_arquivo.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel_arquivoLayout = new javax.swing.GroupLayout(panel_arquivo);
        panel_arquivo.setLayout(panel_arquivoLayout);
        panel_arquivoLayout.setHorizontalGroup(
            panel_arquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_arquivoLayout.setVerticalGroup(
            panel_arquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        main_panel.addTab("Arquivo", panel_arquivo);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_title.png"))); // NOI18N
        icon.setText("jLabel1");

        javax.swing.GroupLayout main_fundoLayout = new javax.swing.GroupLayout(main_fundo);
        main_fundo.setLayout(main_fundoLayout);
        main_fundoLayout.setHorizontalGroup(
            main_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_fundoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(main_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(main_fundoLayout.createSequentialGroup()
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_title, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        main_fundoLayout.setVerticalGroup(
            main_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_fundoLayout.createSequentialGroup()
                .addGroup(main_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_fundoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(text_title))
                    .addGroup(main_fundoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void center(Container container) {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();

        container.setLocation((screen.width - container.getWidth()) / 2, (screen.height - container.getHeight()) / 2);
    }

    private void btn_choose_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choose_pathActionPerformed

        // TODO add your handling code here:
        JFileChooser chooser;
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Escolha o caminho: ");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            input_texto_caminho_arquivo.setText(chooser.getSelectedFile().toString());
        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_btn_choose_pathActionPerformed

    private void btn_texto_CDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_texto_CDActionPerformed
        if (area_texto_mensagem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhuma informação escrita para ser compactada!",
                    "Erro ao compactar", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (input_texto_nome_arquivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o nome do arquivo!",
                    "Erro ao compactar", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (input_texto_caminho_arquivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o caminho do arquivo!",
                    "Erro ao compactar", JOptionPane.ERROR_MESSAGE);
            return;
        }

        FGM_Compacter objeto = new FGM_Compacter();
        objeto.Compactar(area_texto_mensagem.getText());

        System.out.println(objeto.getCabecalho());
        System.out.println(objeto.getTextoCompactado());

        String caminho = input_texto_caminho_arquivo.getText() + "\\" + input_texto_nome_arquivo.getText();

        System.out.println(caminho);
        try {
            
            Save.compactar(
                    caminho,
                    ".fgm",
                    objeto.getCabecalho(),
                    objeto.getTextoCompactado()
            );

            // Abre o local do arquivo compactado
            File file = new File(input_texto_caminho_arquivo.getText());
            Desktop desktop = Desktop.getDesktop();
            desktop.open(file);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar arquivo compactado!",
                    "Erro ao compactar", JOptionPane.ERROR_MESSAGE);
        }

        area_texto_mensagem.setText(null);
        input_texto_nome_arquivo.setText(null);
        input_texto_caminho_arquivo.setText(null);

    }//GEN-LAST:event_btn_texto_CDActionPerformed

    private void btn_choose_path1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choose_path1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser;
        String choosertitle = "";
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Escolha a pasta");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            input_arquivo_caminho_arquivo.setText(chooser.getSelectedFile().toString());
        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_btn_choose_path1ActionPerformed

    private void btn_arquivo_CDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_arquivo_CDActionPerformed
        // TODO add your handling code here:
        if (input_arquivo_a_compactar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um arquivo para compactar!",
                    "Erro ao compactar", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (input_arquivo_nome_arquivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira um nome para o novo arquivo compactado!",
                    "Erro ao compactar", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (input_arquivo_caminho_arquivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione o caminho para salvar o arquivo compactado!",
                    "Erro ao compactar", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String file_caminho = input_arquivo_a_compactar.getText();
        String nome = input_arquivo_nome_arquivo.getText();
        String novo_caminho = input_arquivo_caminho_arquivo.getText();

        if (select_op.getSelectedItem().toString().equals("Descompactar")) {
            
            String[] valores = Save.readFileFGM(file_caminho);
            FGM_Compacter objeto = new FGM_Compacter();
            objeto.Descompactar(valores[0], valores[1]);

            String caminho = novo_caminho + "\\" + nome;

            try {
                Save.salvar(caminho, ".txt", objeto.getTextoDescompactado());
                // Abre o local do arquivo compactado
                File file = new File(novo_caminho);
                Desktop desktop = Desktop.getDesktop();
                desktop.open(file);
                
                resetCamposArquivos();
                
                area_arquivo_texto_D.setText(objeto.getTextoDescompactado());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao descompactar arquivo!",
                        "Erro ao descompactar", JOptionPane.ERROR_MESSAGE);
            }
            
        } else {

            String texto = Save.readFileTxt(file_caminho);

            FGM_Compacter objeto = new FGM_Compacter();
            objeto.Compactar(texto);

            String caminho = novo_caminho + "\\" + nome;

            System.out.println(caminho);
            try {
                Save.compactar(
                        caminho,
                        ".fgm",
                        objeto.getCabecalho(),
                        objeto.getTextoCompactado()
                );

                // Abre o local do arquivo compactado
                File file = new File(novo_caminho);
                Desktop desktop = Desktop.getDesktop();
                desktop.open(file);
                
                resetCamposArquivos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao salvar arquivo compactado!",
                        "Erro ao compactar", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btn_arquivo_CDActionPerformed

    public void resetCamposArquivos(){
        input_arquivo_a_compactar.setText(null);
        input_arquivo_nome_arquivo.setText(null);
        input_arquivo_caminho_arquivo.setText(null);
    }
    
    private void btn_choose_path2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choose_path2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser;
        String choosertitle = "";
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle(choosertitle);

        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        chooser.setAcceptAllFileFilterUsed(false);

        if (select_op.getSelectedItem().toString().equals("Descompactar")) {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("FGM", "fgm");
            chooser.addChoosableFileFilter(filter);
        } else {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("TXT", "txt");
            chooser.addChoosableFileFilter(filter);
        }

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            input_arquivo_a_compactar.setText(chooser.getSelectedFile().toString());
        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_btn_choose_path2ActionPerformed

    private void input_arquivo_a_compactarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_input_arquivo_a_compactarPropertyChange
        // TODO add your handling code here:
        if (!input_arquivo_a_compactar.getText().isEmpty()) {
            btn_arquivo_CD.setEnabled(true);
        }
    }//GEN-LAST:event_input_arquivo_a_compactarPropertyChange

    private void input_arquivo_nome_arquivoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_input_arquivo_nome_arquivoPropertyChange
        // TODO add your handling code here:
        if (!input_arquivo_nome_arquivo.getText().isEmpty()) {
            btn_arquivo_CD.setEnabled(true);
        }
    }//GEN-LAST:event_input_arquivo_nome_arquivoPropertyChange

    private void input_arquivo_nome_arquivoVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_input_arquivo_nome_arquivoVetoableChange
        // TODO add your handling code here:
        if (!input_arquivo_nome_arquivo.getText().isEmpty()) {
            btn_arquivo_CD.setEnabled(true);
        }
    }//GEN-LAST:event_input_arquivo_nome_arquivoVetoableChange

    private void select_opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_opActionPerformed
        if (select_op.getSelectedItem().toString().equals("Descompactar")) {
            this.setViewDescompactar();
        } else {
            this.setViewCompactar();
        }
    }//GEN-LAST:event_select_opActionPerformed

    private void setViewDescompactar() {
        label_arquivo_caminho_CD.setText("Selecione o arquivo p/ descompactar");
        btn_arquivo_CD.setText("Descompactar");
        area_arquivo_texto_D.setVisible(true);
        fundo_area.setVisible(true);
    }

    private void setViewCompactar() {
        label_arquivo_caminho_CD.setText("Selecione o arquivo p/ compactar");
        btn_arquivo_CD.setText("Compactar");
        area_arquivo_texto_D.setVisible(false);
        fundo_area.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_arquivo_texto_D;
    private javax.swing.JTextArea area_texto_mensagem;
    private javax.swing.JButton btn_arquivo_CD;
    private javax.swing.JButton btn_choose_path;
    private javax.swing.JButton btn_choose_path1;
    private javax.swing.JButton btn_choose_path2;
    private javax.swing.JButton btn_texto_CD;
    private javax.swing.JDialog dialog_open_path;
    private javax.swing.JScrollPane fundo_area;
    private javax.swing.JLabel icon;
    private javax.swing.JTextField input_arquivo_a_compactar;
    private javax.swing.JTextField input_arquivo_caminho_arquivo;
    private javax.swing.JTextField input_arquivo_nome_arquivo;
    private javax.swing.JTextField input_texto_caminho_arquivo;
    private javax.swing.JTextField input_texto_nome_arquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_arquivo_caminho_CD;
    private javax.swing.JLabel label_arquivo_nome_C;
    private javax.swing.JLabel label_arquivo_path_arquivo;
    private javax.swing.JLabel label_caminho_arquivo;
    private javax.swing.JLabel label_nome_arquivo;
    private javax.swing.JLabel label_select_op;
    private javax.swing.JPanel main_fundo;
    private javax.swing.JTabbedPane main_panel;
    private javax.swing.JPanel p_panel_texto;
    private javax.swing.JDesktopPane panel_arquivo;
    private javax.swing.JDesktopPane panel_texto;
    private javax.swing.JComboBox<String> select_op;
    private javax.swing.JLabel text_title;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo_title.png")));
    }
}
